<?php
/** @var \MageSuite\Pwa\Block\Data $block */
/** @var \MageSuite\Pwa\Model\Data; $viewModel */
$viewModel = $block->getViewModel();
?>
{
    "name": "<?= $viewModel->getName(); ?>",
    "short_name": "<?= $viewModel->getShortName(); ?>",
    "start_url": "<?= $viewModel->getStartUrl(); ?>",
    "display": "standalone",
    "background_color": "<?= $block->getBackgroundColor(); ?>",
    "theme_color": "<?= $block->getThemeColor(); ?>",
    "description": "<?= $block->getDescription(); ?>",
    "categories": ["<?= implode("\", \"", $block->getCategories()); ?>"],
    "icons": [
        { 
            "src": "<?= $block->getViewFileUrl('Magento_Theme::favicon-16x16.png'); ?>",
            "sizes": "16x16",
            "type": "image/png"
        }, { 
            "src": "<?= $block->getViewFileUrl('Magento_Theme::favicon-32x32.png'); ?>",
            "sizes": "32x32",
            "type": "image/png"
        }, { 
            "src": "<?= $block->getViewFileUrl('Magento_Theme::favicon.ico'); ?>",
            "sizes": "48x48",
            "type": "image/x-icon"
        }, { 
            "src": "<?= $block->getViewFileUrl('Magento_Theme::icon-128x128.png'); ?>",
            "sizes": "128x128",
            "type": "image/png"
        }, {
            "src": "<?= $block->getViewFileUrl('Magento_Theme::icon-144x144.png'); ?>",
            "sizes": "144x144",
            "type": "image/png"
        }, {
            "src": "<?= $block->getViewFileUrl('Magento_Theme::mstile-150x150.png'); ?>",
            "sizes": "150x150",
            "type": "image/png"
        }, {
            "src": "<?= $block->getViewFileUrl('Magento_Theme::icon-152x152.png'); ?>",
            "sizes": "152x152",
            "type": "image/png"
        }, {
            "src": "<?= $block->getViewFileUrl('Magento_Theme::apple-touch-icon.png'); ?>",
            "sizes": "180x180",
            "type": "image/png"
        }, {
            "src": "<?= $block->getViewFileUrl('Magento_Theme::android-chrome-192x192.png'); ?>",
            "sizes": "192x192",
            "type": "image/png"
        }, {
            "src": "<?= $block->getViewFileUrl('Magento_Theme::android-chrome-256x256.png'); ?>",
            "sizes": "256x256",
            "type": "image/png"
        }, {
            "src": "<?= $block->getViewFileUrl('Magento_Theme::icon-512x512.png'); ?>",
            "sizes": "512x512",
            "type": "image/png"
        }
    ]
}