<?php
/** @var \MageSuite\Pwa\Block\Data $block */
/** @var \MageSuite\Pwa\ViewModel\Manifest $viewModel */
$viewModel = $block->getViewModel();
$configuration = $viewModel->getConfiguration();
?>
<meta name="apple-mobile-web-app-status-bar-style" content="<?=/* @noEscape */ $configuration->getThemeColor(); ?>"/>
<meta name="theme-color" content="<?=/* @noEscape */ $configuration->getThemeColor(); ?>"/>
