<?php
/**
 * See documentation: https://web.dev/service-workers-registration/
 * @var $block \MageSuite\Pwa\Block\Data
 * */
$url = $block->getBaseUrl() . 'service-worker.js';
?>
<?php $scriptString = <<<script
if ('serviceWorker' in navigator) {
    window.addEventListener('load', function() {
        navigator.serviceWorker.register('{$url}');
    });
}
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
