<?php
/**
 * Route responsible for caching static files with CDN support.
 */
?>
<?php
/**
 * External URLs have to be fully matched by a RegExp so we need statics' base URL.
 */
$staticBaseUrl = $block->getViewFileUrl('');
?>
<script>
workbox.routing.registerRoute(
  new RegExp('<?= $staticBaseUrl; ?>.+\.(?:png|gif|jpg|jpeg|webp|svg|js|css|html|json)$'),
  new workbox.strategies.CacheFirst({
    cacheName: 'static',
    plugins: [
      new workbox.expiration.Plugin({
        maxEntries: 300,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);
</script>
