<?php
/** @var \MageSuite\Pwa\Block\Data $block */
/** @var \MageSuite\Pwa\ViewModel\Manifest $viewModel */
$viewModel = $block->getViewModel();
$configuration = $viewModel->getConfiguration();
?>
<script>
importScripts('https://storage.googleapis.com/workbox-cdn/releases/6.0.0/workbox-sw.js');

<?php if ($configuration->isDebugModeEnabled()) : ?>
workbox.setConfig({
  debug: true
});

<?php endif; ?>
</script>
