<?php
/** @var \MageSuite\Pwa\Block\Data $block */
/** @var \MageSuite\Pwa\ViewModel\Manifest $viewModel */
$viewModel = $block->getViewModel();
$configuration = $viewModel->getConfiguration();

$scriptString = "
importScripts('https://storage.googleapis.com/workbox-cdn/releases/6.6.0/workbox-sw.js');";

if ($configuration->isDebugModeEnabled()) {
    $scriptString .="workbox.setConfig({
  debug: true
})";
}
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

